name: angry-dragon-fire CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python_version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v2
        with:
          python-version: "${{matrix.python_version}}"
      - name: Run cargo format check
        run: |
          cargo fmt -- --check
      - uses: messense/maturin-action@v1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          maturin-version: latest
          command: build
          target: x64
          args: --release
          manylinux: 2010
      - uses: messense/maturin-action@v1
        if: ${{ matrix.os != 'ubuntu-latest' }}
        with:
          maturin-version: latest
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: target/wheels/*.whl
