name: angry-dragon-fire CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Code style
        run: |
          cargo fmt -- --check
      - name: Print environment
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          set
      - uses: messense/maturin-action@v1
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          maturin-version: latest
          command: build
          target: x64
          args: --release -i python3.9.exe --no-sdist
      - uses: messense/maturin-action@v1
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          maturin-version: latest
          command: build
          args:  --release --universal2 --no-sdist
      - uses: messense/maturin-action@v1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          maturin-version: latest
          command: build
          target: x64
          args: --release
          manylinux: 2014
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            target/wheels/*.whl
            target/wheels/*.tar.gz
